# Generated by Django 5.2.6 on 2025-11-04 07:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='roles_name_a96913_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('OnLeave', 'On Leave'), ('Suspended', 'Suspended')], db_index=True, default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(limit_choices_to={'status': 'Active'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='users.user')),
                ('supervisor', models.ForeignKey(limit_choices_to={'status': 'Active'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignments', to='users.user')),
            ],
            options={
                'db_table': 'supervisor_assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorassignment',
            index=models.Index(fields=['supervisor', 'end_date'], name='supervisor__supervi_2faa94_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorassignment',
            index=models.Index(fields=['officer', 'end_date'], name='supervisor__officer_eacf74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supervisorassignment',
            unique_together={('supervisor', 'officer', 'end_date')},
        ),
    ]
