# Generated by Django 5.2.6 on 2025-11-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_847b48_idx',
        ),
        migrations.AlterUniqueTogether(
            name='supervisorassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddConstraint(
            model_name='supervisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('supervisor', 'officer'), name='unique_active_supervisor_officer'),
        ),
    ]
