# Generated by Django 5.2.6 on 2025-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge_number',
            field=models.CharField(blank=True, db_index=True, help_text='Número de placa del oficial de policía', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, help_text='Rango del oficial de policía', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, help_text='Fotografía del oficial', null=True, upload_to='officers/'),
        ),
    ]
