# Generated by Django 5.2.6 on 2025-10-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('metric_type_id', models.AutoField(primary_key=True)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=20, blank=True)),
            ],
            options={
                'app_label': 'biometrics',
            },
        ),
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('biometric_id', models.BigAutoField(primary_key=True)),
                ('metric_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrics.MetricType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'app_label': 'biometrics',
            },
        ),
        migrations.AddIndex(
            model_name='biometric',
            index=models.Index(fields=['user', 'created_at'], name='biometric_user_created_at_idx'),
        ),
    ]
