# Generated by Django 5.2.8 on 2025-11-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpms', to='users.user')),
            ],
            options={
                'db_table': 'bpm',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bpm_user_id_1de76c_idx')],
            },
        ),
    ]
