# Generated by Django 5.2.6 on 2025-10-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('metric_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('biometric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometrics.metrictype')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='biometrics__user_id_91edea_idx')],
            },
        ),
    ]
