# Generated by Django 5.2.6 on 2025-11-13 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricrecord',
            name='metric_type',
        ),
        migrations.RemoveField(
            model_name='biometricrecord',
            name='user',
        ),
        migrations.CreateModel(
            name='BPM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpms', to='users.user')),
            ],
            options={
                'db_table': 'bpm',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='MetricType',
        ),
        migrations.DeleteModel(
            name='BiometricRecord',
        ),
    ]
