# Generated by Django 5.2.6 on 2025-10-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometrics", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="BiometricRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.DecimalField(decimal_places=3, max_digits=10)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biometrics.metrictype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Biometric",
        ),
        migrations.AddIndex(
            model_name="biometricrecord",
            index=models.Index(
                fields=["user", "recorded_at"], name="biometrics__user_id_1f5835_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricrecord",
            index=models.Index(
                fields=["metric_type", "recorded_at"],
                name="biometrics__metric__6dd3fe_idx",
            ),
        ),
    ]
