# Generated by Django 5.2.8 on 2025-11-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
        ('users', '0002_alter_supervisorassignment_officer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stress_score', models.FloatField(help_text='Score de estrés calculado por ML (0-100)')),
                ('stress_level', models.CharField(choices=[('Muy Bajo', 'Muy Bajo'), ('Bajo', 'Bajo'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Muy Alto', 'Muy Alto')], db_index=True, help_text='Nivel de estrés clasificado', max_length=20)),
                ('requires_alert', models.BooleanField(db_index=True, default=False, help_text='Si el modelo ML recomienda generar una alerta')),
                ('alert_probability', models.FloatField(help_text='Probabilidad de que se requiera alerta (0.0-1.0)')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, help_text='Severidad clasificada por el modelo ML', max_length=20)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, help_text='Si se detectó una anomalía en el patrón cardíaco')),
                ('anomaly_score', models.FloatField(blank=True, help_text='Score de anomalía del Isolation Forest', null=True)),
                ('hr_zone', models.CharField(help_text='Zona cardíaca clasificada (ej: Zone 3 - Moderada)', max_length=50)),
                ('hr_variability', models.FloatField(blank=True, help_text='Variabilidad de la frecuencia cardíaca', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales de la predicción ML')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bpm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_prediction', to='biometrics.bpm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='users.user')),
            ],
            options={
                'db_table': 'ml_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('HR_CRITICAL_LOW', 'Frecuencia Cardíaca Críticamente Baja'), ('HR_CRITICAL_HIGH', 'Frecuencia Cardíaca Críticamente Alta'), ('HR_ZERO', 'Sin Señal de Frecuencia Cardíaca'), ('STRESS_CRITICAL', 'Estrés Crítico'), ('STRESS_HIGH_RISK', 'Alto Riesgo de Estrés'), ('HR_ABNORMALLY_HIGH', 'Frecuencia Cardíaca Anormalmente Alta'), ('HR_ABNORMALLY_LOW', 'Frecuencia Cardíaca Anormalmente Baja'), ('STRESS_ELEVATED', 'Estrés Elevado'), ('HR_SUSTAINED_ELEVATED', 'Frecuencia Cardíaca Elevada Sostenida'), ('HR_RAPID_FLUCTUATION', 'Fluctuaciones Rápidas en FC'), ('ANOMALY_DETECTED', 'Anomalía Detectada'), ('ML_PREDICTION_ALERT', 'Alerta Predictiva ML')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('message', models.TextField(help_text='Mensaje descriptivo de la alerta')),
                ('action_required', models.TextField(help_text='Acción recomendada para esta alerta')),
                ('heart_rate', models.FloatField()),
                ('stress_score', models.FloatField()),
                ('stress_level', models.CharField(max_length=20)),
                ('requires_immediate_action', models.BooleanField(db_index=True, default=False, help_text='Si requiere acción inmediata (CRITICAL/HIGH)')),
                ('is_anomaly', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], db_index=True, default='Pending', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales de la alerta ML')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_ml_alerts', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_alerts', to='users.user')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='biometrics.mlprediction')),
            ],
            options={
                'db_table': 'ml_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['user', 'created_at'], name='ml_predicti_user_id_7a7b16_idx'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['user', 'requires_alert'], name='ml_predicti_user_id_4c5a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['stress_level', 'created_at'], name='ml_predicti_stress__0419b6_idx'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['severity', 'created_at'], name='ml_predicti_severit_201c80_idx'),
        ),
        migrations.AddIndex(
            model_name='mlalert',
            index=models.Index(fields=['user', 'status'], name='ml_alerts_user_id_b8d927_idx'),
        ),
        migrations.AddIndex(
            model_name='mlalert',
            index=models.Index(fields=['severity', 'status'], name='ml_alerts_severit_ac32b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mlalert',
            index=models.Index(fields=['created_at', 'status'], name='ml_alerts_created_eca756_idx'),
        ),
        migrations.AddIndex(
            model_name='mlalert',
            index=models.Index(fields=['user', 'requires_immediate_action'], name='ml_alerts_user_id_dc468a_idx'),
        ),
    ]
