# Generated by Django 5.2.8 on 2025-12-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_mlprediction_mlalert_and_more'),
        ('users', '0002_alter_supervisorassignment_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprediction',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Notas de resolución/justificación'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se resolvió', null=True),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que resolvió la predicción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_predictions', to='users.user'),
        ),
        migrations.AddField(
            model_name='mlprediction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Acknowledged', 'Reconocida'), ('Resolved', 'Resuelta'), ('Dismissed', 'Descartada')], db_index=True, default='Pending', help_text='Estado de la predicción', max_length=20),
        ),
    ]
