# Generated by Django 5.2.6 on 2025-11-13 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_remove_biometricrecord_metric_type_and_more'),
        ('users', '0002_remove_user_users_is_acti_847b48_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bpm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bpm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='bpm',
            index=models.Index(fields=['user', 'created_at'], name='bpm_user_id_1de76c_idx'),
        ),
    ]
