# Generated by Django 5.2.6 on 2025-11-25 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('biometrics', '0002_remove_biometricrecord_metric_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stress_score', models.FloatField(help_text='Stress score from 0-100')),
                ('stress_level', models.CharField(choices=[('Muy Bajo', 'Muy Bajo'), ('Bajo', 'Bajo'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Muy Alto', 'Muy Alto')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('requires_alert', models.BooleanField(db_index=True, default=False)),
                ('alert_probability', models.FloatField(help_text='Probability of requiring alert (0.0-1.0)')),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('hr_zone', models.CharField(blank=True, max_length=50)),
                ('ml_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predictions', to='alerts.alert')),
                ('bpm_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='biometrics.bpm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='users.user')),
            ],
            options={
                'db_table': 'ml_predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ml_predicti_user_id_7a7b16_idx'), models.Index(fields=['requires_alert', 'created_at'], name='ml_predicti_require_7841d3_idx'), models.Index(fields=['is_anomaly', 'created_at'], name='ml_predicti_is_anom_2ee4e4_idx'), models.Index(fields=['stress_level', 'created_at'], name='ml_predicti_stress__0419b6_idx')],
            },
        ),
    ]
