# Generated by Django 5.2.8 on 2025-11-30 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('geolocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocations', to='users.user')),
            ],
            options={
                'db_table': 'geolocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='geolocation_user_id_6adef2_idx'), models.Index(fields=['created_at'], name='geolocation_created_4d9d11_idx')],
            },
        ),
    ]
