# Generated by Django 5.2.6 on 2025-10-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('geolocation_id', models.BigAutoField(primary_key=True)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'app_label': 'geolocation',
            },
        ),
        migrations.AddIndex(
            model_name='geolocation',
            index=models.Index(fields=['user', 'created_at'], name='geolocation_user_created_at_idx'),
        ),
    ]
