# Generated by Django 5.2.6 on 2025-10-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="id",
            new_name="report_id",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="type",
            new_name="report_type",
        ),
    ]
