# Generated by Django 5.2.6 on 2025-11-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Exercise', 'Exercise'), ('Nutrition', 'Nutrition'), ('Sleep', 'Sleep'), ('Mental', 'Mental Health'), ('Other', 'Other')], db_index=True, default='Other', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.user')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_f904a9_idx'), models.Index(fields=['category', 'priority'], name='recommendat_categor_377546_idx')],
            },
        ),
    ]
