# Generated by Django 5.2.8 on 2025-12-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0002_alter_supervisorassignment_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_recommendations', to='users.user'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], db_index=True, default='Pending', max_length=20),
        ),
    ]
