# Generated by Django 5.2.8 on 2025-12-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendation_resolution_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('Salud', 'Salud'), ('Ejercicio', 'Ejercicio'), ('Nutrición', 'Nutrición'), ('Descanso', 'Descanso'), ('Mental', 'Salud Mental'), ('Otro', 'Otro')], db_index=True, default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], db_index=True, default='Media', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Reconocida', 'Reconocida'), ('Resuelta', 'Resuelta')], db_index=True, default='Pendiente', max_length=20),
        ),
    ]
