
# ---------------------------------------------------------------------------- #

''' Django settings for Artemis project.
    Generated by 'django-admin startproject' using Django 5.2.7.

    For more information on this file, see:
        https://docs.djangoproject.com/en/5.2/topics/settings/

    For the full list of settings and their values, see:
        https://docs.djangoproject.com/en/5.2/ref/settings/
'''

# ---------------------------------------------------------------------------- #

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production.
# See: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ---------------------------------------------------------------------------- #

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d1hes9vk7l4+x+@tr6m@+!u=pv3oe#ju1j=bc*_8^f!##8az@!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ---------------------------------------------------------------------------- #

ALLOWED_HOSTS = []

# ---------------------------------------------------------------------------- #

LOCAL_APPS = [ 'apps.Dashboard' ]

THIRD_PARTY_APPS = [
    # ...
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

] + LOCAL_APPS + THIRD_PARTY_APPS

# ---------------------------------------------------------------------------- #

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------------------------------------------------------- #

ROOT_URLCONF = 'Artemis.urls'

# ---------------------------------------------------------------------------- #

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------------------------------------------------------- #

WSGI_APPLICATION = 'Artemis.wsgi.application'

# ---------------------------------------------------------------------------- #

# Database: https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'Artemis.sqlite3',
    }
}

# ---------------------------------------------------------------------------- #

# Password validation: https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------------------------------------------------------- #

# Internationalization: https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Tijuana'

USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------------- #

# Static files (CSS, JavaScript, Images): https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'statics' ]

# ---------------------------------------------------------------------------- #

# Default primary key field type: https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------- #

# Login URLs: https://docs.djangoproject.com/en/5.1/ref/settings/#login-redirect-url
LOGIN_URL = '/artemis/login/'
LOGIN_REDIRECT_URL = '/artemis/'
LOGOUT_REDIRECT_URL = '/artemis/login/'

# ---------------------------------------------------------------------------- #