# Generated by Django 5.2.6 on 2025-11-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Alert', 'Alert'), ('Report', 'Report'), ('System', 'System'), ('Other', 'Other')], db_index=True, default='Other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.user')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='events_user_id_3ca773_idx'), models.Index(fields=['category', 'created_at'], name='events_categor_807793_idx')],
            },
        ),
    ]
