# Generated by Django 5.2.6 on 2025-11-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Login_Failed', 'Login Failed'), ('Password_Changed', 'Password Changed'), ('Password_Reset', 'Password Reset'), ('Session_Expired', 'Session Expired'), ('Access_Denied', 'Access Denied'), ('Biometric_Capture_Success', 'Biometric Capture Success'), ('Biometric_Capture_Failed', 'Biometric Capture Failed'), ('Fingerprint_Registered', 'Fingerprint Registered'), ('Face_Verified', 'Face Verified'), ('Iris_Verified', 'Iris Verified'), ('Biometric_Data_Deleted', 'Biometric Data Deleted'), ('Biometric_Match_Found', 'Biometric Match Found'), ('Biometric_Match_Not_Found', 'Biometric Match Not Found'), ('Location_Changed', 'Location Changed'), ('Geofence_Violated', 'Geofence Violated'), ('Suspicious_Location_Access', 'Suspicious Location Access'), ('Location_Tracked', 'Location Tracked'), ('Recommendation_Generated', 'Recommendation Generated'), ('Recommendation_Accepted', 'Recommendation Accepted'), ('Recommendation_Rejected', 'Recommendation Rejected'), ('Alert', 'Alert'), ('Report', 'Report'), ('Alert_Triggered', 'Alert Triggered'), ('Alert_Resolved', 'Alert Resolved'), ('User_Created', 'User Created'), ('User_Deleted', 'User Deleted'), ('User_Modified', 'User Modified'), ('Role_Changed', 'Role Changed'), ('Configuration_Changed', 'Configuration Changed'), ('Admin_Access', 'Admin Access'), ('Data_Exported', 'Data Exported'), ('Data_Imported', 'Data Imported'), ('Data_Deleted', 'Data Deleted'), ('System', 'System'), ('System_Error', 'System Error'), ('System_Warning', 'System Warning'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
    ]
