# Generated by Django 5.2.6 on 2025-10-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="id",
            new_name="event_id",
        ),
    ]
