# Generated by Django 5.2.6 on 2025-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
